### ISSUE TITLE
Nonblocking sockets are not working

### ISSUE THREAD

**Issue by jarulo** [switchbrew/libnx#100]
**Observed behavior:**
Using a non-blocking socket with connect to google.com:80 always returns -1.

**Expected behavior:**
After a certain delay, it is expected that retrying the call to connect on the same sockfd would succeed.

**Comment by yellows8** [comment]
What's errno?

**Comment by WinterMute** [comment]
Just checked this, errno is EINPROGRESS (or at least it will be with https://github.com/switchbrew/libnx/pull/118)
