### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by mailwl** [switchbrew/libnx#128]
latest devkitA64, WSL (Ubuntu 16.04)

```
/home/wl/libnx/nx/source/runtime/newlib.c: In function 'newlibSetup':
/home/wl/libnx/nx/source/runtime/newlib.c:130:15: error: '__syscalls_t {aka struct <anonymous>}' has no member named 'nanosleep'
     __syscalls.nanosleep = __libnx_nanosleep;
```

**Comment by fincs** [comment]
Are you sure you have the latest devkitA64? It doesn't look like that to me at all.

**Comment by mailwl** [comment]
yes, right. bad knowing of pacman

**Comment by rpalmon** [comment]
@mailwl what did you do to fix it? I would like to know myself.

**Comment by WinterMute** [comment]
@rpalmon sudo (dkp-)pacman -Syu

**Comment by rpalmon** [comment]
@WinterMute  Is there a command for windows?

**Comment by mailwl** [comment]
i suppose, on windows there is installer with GUI

**Comment by WinterMute** [comment]
@rpalmon 

Click start->devkitPro->Msys2

In the shell that opens type pacman -Syu
