### ISSUE TITLE
SDMC file (fopen) opening seems broken

### ISSUE THREAD

**Issue by lantus** [switchbrew/libnx#137]
I am having issues with latest libnx (1.3) and RyuJinx. In the past SDMC fs loading worked fine, but now  I get the following error in RyuJinx on the fopen() line below

`00:00:05.873 | 0005 KernelSvc SvcArbitrateLock: Invalid owner thread handle `0x08006e40!`

this piece of code would work fine  . Has anything changed with regards to sdmc file management in 1.3? This should be reproducable - please try this code out with RyuJinx  (any version) below 

`int main(int argc, char **argv)
{
	gfxInitDefault();
	consoleInit(NULL);
 
	FILE *f = fopen("test.txt","r");
	
	if (f)
	{
		printf("SDMC file opened ok\n");		
		fclose(f);
	}	 
	 
	
	// Main loop
	while(appletMainLoop())
	{
		//Scan all the inputs. This should be done once for each frame
		hidScanInput();

		//hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
		u32 kDown = hidKeysDown(CONTROLLER_P1_AUTO);

		if (kDown & KEY_PLUS) break; // break in order to return to hbmenu

		gfxFlushBuffers();
		gfxSwapBuffers();
		gfxWaitForVsync();
	}

	gfxExit();
	return 0;
}`

Edit: if i link with libnx V1.21 it opens the file normally as expected

**Comment by fincs** [comment]
Can you try updating to latest devkitA64? (Use `pacman -Syu` to upgrade)

**Comment by lantus** [comment]
```
$ pacman -Syu
:: Synchronizing package databases...
 msys is up to date
 dkp-libs is up to date
 dkp-windows is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

 there is no change. for now i have reverted back to libnx1.21

**Comment by fincs** [comment]
I believe this was fixed with aa3c35e6e3649. Can you try libnx at that particular commit?

**Comment by lantus** [comment]
tried that, now i get an error

```
$ make
make -C nx/
make[1]: Entering directory '/opt/devkitpro/dev/libnx/nx'
default_font.bin
argv.c
aarch64-none-elf-gcc -MMD -MP -MF /opt/devkitpro/dev/libnx/nx/release/argv.d -g -Wall -Werror -ffunction-sections -fdata-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -DNDEBUG=1 -O2 -I/opt/devkitpro/dev/libnx/nx/include -I/opt/devkitpro/dev/libnx/nx/external/bsd/include  -I. -iquote /opt/devkitpro/dev/libnx/nx/include/switch/ -DSWITCH -c /opt/devkitpro/dev/libnx/nx/source/runtime/argv.c -o argv.o
nacp.c
aarch64-none-elf-gcc -MMD -MP -MF /opt/devkitpro/dev/libnx/nx/release/nacp.d -g -Wall -Werror -ffunction-sections -fdata-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -DNDEBUG=1 -O2 -I/opt/devkitpro/dev/libnx/nx/include -I/opt/devkitpro/dev/libnx/nx/external/bsd/include  -I. -iquote /opt/devkitpro/dev/libnx/nx/include/switch/ -DSWITCH -c /opt/devkitpro/dev/libnx/nx/source/runtime/nacp.c -o nacp.o
newlib.c
aarch64-none-elf-gcc -MMD -MP -MF /opt/devkitpro/dev/libnx/nx/release/newlib.d -g -Wall -Werror -ffunction-sections -fdata-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -DNDEBUG=1 -O2 -I/opt/devkitpro/dev/libnx/nx/include -I/opt/devkitpro/dev/libnx/nx/external/bsd/include  -I. -iquote /opt/devkitpro/dev/libnx/nx/include/switch/ -DSWITCH -c /opt/devkitpro/dev/libnx/nx/source/runtime/newlib.c -o newlib.o
F:/devkitPro/dev/libnx/nx/source/runtime/newlib.c: In function 'newlibSetup':
F:/devkitPro/dev/libnx/nx/source/runtime/newlib.c:130:15: error: '__syscalls_t {aka struct <anonymous>}' has no member named 'nanosleep'
     __syscalls.nanosleep = __libnx_nanosleep;
               ^
make[2]: *** [/opt/devkitpro/devkitA64/base_rules:19: newlib.o] Error 1
make[1]: *** [Makefile:124: lib/libnx.a] Error 2
make[1]: Leaving directory '/opt/devkitpro/dev/libnx/nx'
make: *** [Makefile:2: all] Error 2

```

**Comment by fincs** [comment]
That sounds like you have an old build of devkitA64 installed somehow. I'd advise you to nuke your entire toolchain installation and [start over from scratch](https://devkitpro.org/wiki/Getting_Started).

**Comment by WinterMute** [comment]
Update your tools, you're using an old version of devkitA64 ...

**Comment by fincs** [comment]
The mismatched devkitA64 version would also be a potential explanation for the weird SVC error too.

**Comment by lantus** [comment]
The fopen() error ive initially reported is with the libnx 1.3 static lib from the updater. Rather than throw doubt on me , why not try out yourself? 

I will try a clean devkitA64 WinterMute , hopefully that will resolve the link error for me

**Comment by fincs** [comment]
The prebuilt libnx binaries we ship through pacman are built with the very latest version of devkitA64. Since, upon trying to compile libnx, you got an error message related to __syscalls (which is part of the custom C stdlib we ship with devkitA64), you clearly do not have installed the very latest version of devkitA64.

**Comment by lantus** [comment]
im taking about the original fopen() problem i reported with libnx 1.3 via pacman. No one who builds homebrew will have any success opening files linking with 1.3 release.

**Comment by lantus** [comment]
i am closing this issue now. with a complete wipe and reinstall of devkitA64, i am able to checkout and build latest libnx which addresses the fopen() problem as suggested above
