### ISSUE TITLE
vibration does not work

### ISSUE THREAD

**Issue by MingchenZhang** [switchbrew/libnx#148]
The vibration example in the switchbrew/switch-examples doesn't work. Both hidInitializeVibrationDevices() and hidSendVibrationValues() returned successful code, but vibration does not appear on the joycon. 
I had posted an issue in the switchbrew/switch-examples, but not much discussion happened there, so i re-posted here.

**Comment by yellows8** [comment]
https://github.com/switchbrew/switch-examples/issues/34 for reference

**Comment by yellows8** [comment]
Can someone on 4.x try this?

**Comment by yellows8** [comment]
Still waiting for someone to try this with an application launched by Home Menu.

**Comment by fincs** [comment]
I tried latest commit on 5.1 (with hbl though). irsensor works, but vibration doesn't.
