### ISSUE TITLE
appletLockExit() not working

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [switchbrew/libnx#184]
The usage shown [here](https://github.com/ThatNerdyPikachu/Tinfoil/blob/master/source/main.cpp#L116) and [here](https://github.com/ThatNerdyPikachu/Tinfoil/blob/master/source/main.cpp#L212) does not do anything, am I doing something wrong?

**Comment by yellows8** [comment]
There doesn't seem to be anything post-main-loop that would delay exiting with normal-exit, so ofc it wouldn't be noticeable...

**Comment by ThatNerdyPikachu** [comment]
🤔 But the home button is still usable...

What are you saying?

**Comment by ThatNerdyPikachu** [comment]
I thought appletLockExit() stopped exiting until unlock was called, no?

**Comment by yellows8** [comment]
appletMainLoop() will return false when locking is enabled & HOME is pressed.

**Comment by ThatNerdyPikachu** [comment]
So effectivly, the loop will continue?

**Comment by yellows8** [comment]
no

**Comment by ThatNerdyPikachu** [comment]
w h a t

so we can only delay home button pressing, not stop it?

**Comment by yellows8** [comment]
You could ignore appletMainLoop() retval in some cases if you really want to, but Home Menu would display a waiting-dialog until main() returns. This is for delaying exit so that the app can do proper cleanup, not block it entirely.

**Comment by yellows8** [comment]
See appletBeginBlockingHomeButton (applet-application-only though).
