### ISSUE TITLE
ipc: extra alignment bytes at the end of request rawdata

### ISSUE THREAD

**Issue by misson20000** [switchbrew/libnx#191]
This pattern used all over the library include extraneous padding bytes at the end of the rawdata, since `sizeof(struct)` is padded up to match the stride address. In this case, `sizeof(*raw)` is `u64 magic + u64 cmd_id + u32 flags + u32 padding = 16 bytes` instead of the correct `12 bytes`. Official server code permits extra rawdata, but I don't think official client code includes this padding.

https://github.com/switchbrew/libnx/blob/ac853db5f05adcd4eb50ea03d3f9692516413836/nx/source/services/fs.c#L796-L802

**Comment by yellows8** [comment]
Known old issue.

**Comment by plutooo** [comment]
Yeah, I got sloppy when we realized it didn't matter :p

**Comment by fincs** [comment]
This issue is fixed with the new IPC redesign; and according to CMIF marshalling rules, arguments are ordered from lowest to highest required alignment, which ensures that no extra padding will need to be inserted at the end of the raw data payload.
