### ISSUE TITLE
Joycon attach/detach function

### ISSUE THREAD

**Issue by jonyluke** [switchbrew/libnx#194]
Is there a function for detecting when joycons have been attach or detach?

**Comment by jonyluke** [comment]
I want to do an action when joycon is attach and joycon is dettach.

**Comment by yellows8** [comment]
Attached to handheld?

**Comment by jonyluke** [comment]
Yes

**Comment by yellows8** [comment]
hidGetHandheldMode

**Comment by jonyluke** [comment]
I don't want to know if it it in Handheld mode, i want to know for example, when attaching the right Joycon  playing a sound, and the same wen detaching, is that possible?

**Comment by yellows8** [comment]
https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/hid.h#L653

**Comment by jonyluke** [comment]
I think that is not exactly what I need.

Something like this:
https://www.youtube.com/watch?v=zUDSW22_cOQ

**Comment by yellows8** [comment]
Just use hidGetHandheldMode() or hidIsControllerConnected({handheld})

**Comment by jonyluke** [comment]
But if you attach or detach the joycon you are not still in HandHeldMode?

**Comment by yellows8** [comment]
hidGetHandheldMode willl change when you attach/detach a joycon from the handheld when there's a different joycon attached. hidIsControllerConnected({handheld}) will change for {no joycons attached} / {any joycons attached}.

**Comment by jonyluke** [comment]
With  hidIsControllerConnected({handheld}) do you mean hidIsControllerConnected(CONTROLLER_P1_AUTO); ?

**Comment by yellows8** [comment]
CONTROLLER_HANDHELD

**Comment by jonyluke** [comment]
What do you think of this?

bool mode =  hidIsControllerConnected(CONTROLLER_HANDHELD);
		if(mode){
			//attach
		}
		else{
			//detach
		}

**Comment by jonyluke** [comment]
Nothing happens
```

bool rfirst = true;
bool attach = false;

while (appletMainLoop())
	{
		if(rfirst)
		{
			rfirst = false;
			attach = (hidIsControllerConnected(CONTROLLER_HANDHELD));
		}
		bool nattach = (hidIsControllerConnected(CONTROLLER_HANDHELD));
		if(nattach != attach)
		{
			attach = nattach;
			if(nattach){
				playMp3("attach.mp3");
			}
			else{
				playMp3("dettach.mp3");
			}	
		}
	}

```

**Comment by yellows8** [comment]
hidScan + other main-loop stuff missing.

**Comment by jonyluke** [comment]
Okay that is working when the two joycons are connected or not, but how i do with only one?

**Comment by yellows8** [comment]
Don't really support detecting which joycons are connected when there's at least one connected already.

**Comment by yellows8** [comment]
FWIW, appletMainLoop should not be used when applet is not initialized (didn't realize this was for a sysmodule eariler).

**Comment by jonyluke** [comment]
I'll have to keep looking for an alternative, because when the joycon connects, a few seconds pass, and does not give the effect I want to give him, like detachin the joycon.

**Comment by yellows8** [comment]
There doesn't seem to be an Event for this with the hid service, dunno for hid:sys (but we don't impl the latter service at all atm).

**Comment by jonyluke** [comment]
I managed to do it using gpio
