### ISSUE TITLE
Creating an XCI with my homebrew (nso) cause a kernel panic

### ISSUE THREAD

**Issue by SwitchMods** [switchbrew/libnx#196]
I decided to try to create an XCI from scratch with my homebrew. I've put my main (nso) and my main.npdm in the exeFS, then I've generated the NCA (I've also generated the control NCA with the nacp file and the icons), and finally I've generated the meta NCA.
I'm able to mount the XCI without problems, but when I boot it, I get this kernel panic:

> 2001-0125 

According to switchbrew this should correspond to : 

> Process already started/Wrong memory permission?

It would be cool if someone of the devs could give it a look.

Thanks

**Comment by fincs** [comment]
Referring to https://github.com/switchbrew/libnx/issues/195#issuecomment-433722910
