### ISSUE TITLE
Unable to compile nxloader after devkitpro latest update 

### ISSUE THREAD

**Issue by M-Teix** [switchbrew/libnx#199]
Unable to compile nxloader 2.0.0 after latest devkitpro update (worked prior) 
Errors. 
Service host must be an array!
Failed to parse descriptor json!

**Comment by yellows8** [comment]
Should've been in the actual nx-hbloader repo - fixed by merging this: https://github.com/switchbrew/nx-hbloader/pull/6

Why aren't you using the nx-hbloader release though?

**Comment by M-Teix** [comment]
wasn't sure if is a change in libnx that broke or hbloader. They made it seem like it would work with the old .json format would still work so wasn't sure if it was that.
