### ISSUE TITLE
All timestamps returning 0 when using the stat function

### ISSUE THREAD

**Issue by Datamats** [switchbrew/libnx#204]
After talking with @yellows8 this seems to only be possible to implement on 3.0.0+, but I guess earlier version can keep returning 0.

**Comment by yellows8** [comment]
Need to impl 3.0.0+ GetFileTimeStampRaw & parse output.

**Comment by yellows8** [comment]
Can someone check the 3 timestamps for sd "/hbmenu.nro" on pc/whatever, then run this with "nxlink -s sdmc.nro"? 
[sdmc.zip](https://github.com/switchbrew/libnx/files/2593002/sdmc.zip)

Post/gist the above 3 timestamps and the nxlink output after the file-listing.

**Comment by Datamats** [comment]
Time returned from stat
```
Access: 2018-11-12 01:00:00.000000000 +0100
Modify: 2018-11-12 19:11:50.000000000 +0100
Change: 2018-10-21 12:07:44.000000000 +0200
```
sdmc.nro's output over nxlink
```
rc = 0x0
u64s: 0x5be9c266, 0x5bcc4ff0, 0x5be8c280, u8 = 0x1
stat ret: 0
ctime:   Mon Nov 12 01:00:00 2018
atime:   Sun Oct 21 11:07:44 2018
mtime:   Mon Nov 12 19:11:50 2018
fstat ret: 0
ctime:   Mon Nov 12 01:00:00 2018
atime:   Sun Oct 21 11:07:44 2018
mtime:   Mon Nov 12 19:11:50 2018
```

**Comment by yellows8** [comment]
Repeat the above with this: 
[sdmc.zip](https://github.com/switchbrew/libnx/files/2600489/sdmc.zip)

**Comment by joel16** [comment]
Hey @yellows8 does 3.00+ mean 3.00 inclusive or > 3.00.

Because I get this:
```
rc = 0x177202
u64s: 0x0, 0x0, 0x0, u8 = 0x0
stat ret: 0
ctime:   Wed Dec 31 18:00:00 1969
atime:   Wed Dec 31 18:00:00 1969
mtime:   Wed Dec 31 18:00:00 1969
fstat ret: 0
ctime:   Wed Dec 31 18:00:00 1969
atime:   Wed Dec 31 18:00:00 1969
mtime:   Wed Dec 31 18:00:00 1969
```

**Comment by yellows8** [comment]
@Datamats  [sdmc.zip](https://github.com/switchbrew/libnx/files/2601149/sdmc.zip)

@joel16 Odd, what sysver? Command was added on 3.0.0, that error indicates that the IFilesystem doesn't implement it.

**Comment by Datamats** [comment]
```
rc = 0x0
u64s: 0x5bcc4ff0, 0x5be9c266, 0x5be8c280, u8 = 0x1
stat ret: 0
ctime:   Sun Oct 21 11:07:44 2018
atime:   Mon Nov 12 01:00:00 2018
mtime:   Mon Nov 12 19:11:50 2018
fstat ret: 0
ctime:   Sun Oct 21 11:07:44 2018
atime:   Mon Nov 12 01:00:00 2018
mtime:   Mon Nov 12 19:11:50 2018
```

**Comment by yellows8** [comment]
perfect :)
