### ISSUE TITLE
Simulate press button

### ISSUE THREAD

**Issue by jonyluke** [switchbrew/libnx#210]
Is there a function or something that for example press button A, without touching the button physically?

**Comment by jakibaki** [comment]
There definitely is no such thing in libnx right now but there are ipcs that sound like this might not be a huge undertaking to add.

https://reswitched.github.io/SwIPC/ifaces.html#nn::hid::IHidDebugServer(0)

https://reswitched.github.io/SwIPC/ifaces.html#nn::hid::IHidServer(1)

**Comment by yellows8** [comment]
What use-case? For overriding input in another process? If so, the above doesn't really apply... #152

**Comment by jonyluke** [comment]
It is for doing a module to automate games, for example in Mario Party, you can leave the game playing itself pressing A all the time and return when you want to play as usual.

**Comment by yellows8** [comment]
Yeah no, see #152

**Comment by yellows8** [comment]
3e39f97fe5d1773b3f72a549bb550b7418b75701 https://github.com/switchbrew/switch-examples/commit/b074eb7a4f5eab86dfc5461c63ab77f047580eac
