### ISSUE TITLE
usbHsAcquireUsbIf doesn't seem to be correct

### ISSUE THREAD

**Issue by ischeinkman** [switchbrew/libnx#226]
According to [swipc-gen](https://yls8.mtheall.com/ninupdates/sysupdatedl/autodl_sysupdates/11-19-18_07-05-09-hac/0100000000000006/v404750376/swipcgen_server.info), `usbHsAcquireUsbIf` has 2 output buffers instead of just 1. However, even with adding a second buffer to the IPC command, the call just ends up zeroing both buffers and not returning a handle, nor an error code. 

I tried manipulating the passed in device ID (since it seems to actually be structured as 2 bytes of padding and then a little-endian s16, instead of a full s32), but I could never seem to get different behavior, even with the examples.

**Comment by yellows8** [comment]
code?

**Comment by misson20000** [comment]
This command has changed in at least 2.0.0 and 3.0.0. Which firmware version are you on?

**Comment by ischeinkman** [comment]
6.20

**Comment by yellows8** [comment]
Do not use fprintf in IPC funcs, TLS will get overwritten...

**Comment by ischeinkman** [comment]
I noticed that myself a bit ago too. 

Seems like I'm actually getting an error code of USB: 204 in the response struct.

**Comment by yellows8** [comment]
Try removing all logging in that func, & test + update-gist.

**Comment by ischeinkman** [comment]
Sorry, I guess I am not being clear. 

When I make the first call to `serviceIpcDispatch`, the response contains an error code of 0xcc8c. However, since I have `fprintf`calls between the `serviceIpcDispatch` call and the `serviceIpcParse` call, this response is overwritten in the buffer and leads to the function attemptint to call `_usbHsGetEvent` on a non-existent `ClientIfSession`, which leads to an error code of 0xf601 which the function then returns.

**Comment by ischeinkman** [comment]
When I remove the logging in the function it then returns 0xcc8c.

**Comment by yellows8** [comment]
Cmd changed with 3.0.0, need to add support.

**Comment by yellows8** [comment]
Can you revert all local changes & test e9cc565?

**Comment by ischeinkman** [comment]
Looks like the buffer locations are off:

https://gist.github.com/ischeinkman/b34c56e719ffc3d60e6ba077de109788

**Comment by yellows8** [comment]
So it works fine besides that?

**Comment by yellows8** [comment]
Can you hexdump inf_session.inf?

**Comment by ischeinkman** [comment]
Sorry for going dark; I ended up quickly patching my local copy and then forgot to update here.
The following code ends up successfully creating byte-identical values for `s->inf` and `interface`:

```C
    if (!kernelAbove300()) {
        ipcAddRecvBuffer(&c, &s->inf.inf, sizeof(UsbHsInterfaceInfo), BufferType_Normal);
    }
    else {
        size_t ba_size = offsetof(UsbHsInterfaceInfo, output_endpoint_descs[12]);
        size_t bb_size = sizeof(UsbHsInterface) - ba_size;
        u8 * raw_ptr = (u8 *) &s->inf.inf;
        ipcAddRecvBuffer(&c, raw_ptr + bb_size, ba_size, BufferType_Normal);
        ipcAddRecvBuffer(&c, raw_ptr, bb_size, BufferType_Normal);
    }
```

**Comment by yellows8** [comment]
try this: https://gist.github.com/yellows8/d8be9358249a72c88414901a0e7ae9cd

**Comment by fincs** [comment]
Pinging @ischeinkman - this is the last thing holding back a release.

**Comment by ischeinkman** [comment]
Sorry about that -- once I realized that my local code was working I got too distracted finishing up my usb drive library ([shameless plug](https://github.com/ischeinkman/nx-fatdrive)).

Yes, that code seems to be working exactly the same as the one I had before. Thank you for all the help!
