### ISSUE TITLE
Need link to doxygen url in readme.md

### ISSUE THREAD

**Issue by rsn8887** [switchbrew/libnx#238]
The libnx doxygen site is really hard to find. Why not put a link here in the readme.md? Thanks!

**Comment by fincs** [comment]
Hm? It's up there below the description, being prominently featured...

![image](https://user-images.githubusercontent.com/581494/51792546-de5c5880-21b2-11e9-9f08-73d53917ef50.png)

**Comment by rsn8887** [comment]
I failed to see it, I guess I have become used to ignore descriptions and focus on readme.md :)
