### ISSUE TITLE
[Request] Use built-in controller HOME button light

### ISSUE THREAD

**Issue by cucholix** [switchbrew/libnx#240]
Cosmetic fun request, the right Joy Con, and Switch Pro Controller have a built-in light blue ring in the HOME button, it seems Nintendo have them for some use in the future but they are sitting there in both controllers. When connected to PC and using them as Steam controller the light turns on.

It could be cool to have an option to turn on/off this light upon Switch boot.

Regards

**Comment by fennectech** [comment]
I support the idea to allow applications to control this light.  For example FTPD could turn it on when there is a connection.

**Comment by yellows8** [comment]
Could never find the dedicated hid serv-cmd controlling that, it might not exist (?).

**Comment by yellows8** [comment]
Reopening since [7.0.0+] added a hid:sys serv-cmd for this.

**Comment by yellows8** [comment]
Implemented via recent commits, still need to fill in the struct for it though.
