### ISSUE TITLE
Problem with getaddrinfo() and gethostbyname()

### ISSUE THREAD

**Issue by rsn8887** [switchbrew/libnx#250]
I need getaddrinfo for networking in OpenTTD. https://github.com/rsn8887/OpenTTD/blob/836a341b55e46f839d51a4f86635b7ab52925bc9/src/network/core/address.cpp#L248
And in general it would be nice to have it working on the Switch.

However, I seem to have stumbled upon a bug, or I am missing something:
- `int e=getaddrinfo(...);` is supposed to return a valid error number `e`, but `gai_strerror(e)` gives me "unknown error" clearly something is wrong. 
- I checked that I am submitting a valid address, "content.openttd.org" and valid port 3978. I tried family AF_UNSPEC (default) and AF_INET, to make sure it is not ipv6 that is the problem.
- The error number I get is "22"
- The max possible number should be "15", according to https://linux.die.net/man/3/getaddrinfo and the libnx header `nx/external/bsd/include/netdb.h` 
- It looks to me as if the getaddrinfo implementation is taking that error from `sfdnsresGetAddrInfo,` which ultimately traces back to ipcparse.
https://github.com/switchbrew/libnx/blob/567828f44ee046167793d6572edd1e937a4d96ed/nx/include/switch/kernel/ipc.h#L407
- The rough call sequence initiated internally by getaddrinfo is this: getaddrinfo -> sfdnsresGetAddrInfo -> _sfdnsresDnsRequestCommand -> _sfdnsresDispatchDnsRequest -> _sfdnsresDispatchCommand -> ipcParse and somehow an error 22 pops out in the end.

Which brings me to the questions:
- Is there anything special I have to do (compiler flags etc.) to make getaddrinfo() work on Switch?
- Is there any software that used this succesfully?
- Looking for a working example, I saw that switch-libcurl is configured with "--disable-ipv6 --disable-unix-sockets". Is that maybe related?
- At least two recent commits seem to have fixed some problems in ipc-related structs by adding the ALIGNED attribute. See  https://github.com/switchbrew/libnx/commit/966d554e7d60cdc289b1b48e933a032a04e608fc and https://github.com/switchbrew/libnx/commit/9f45bb4d7e25f81aac121c9e190c0975552bbb31
In the sequence of function calls initiated via getaddrinfo, a similar structure is used. Could this be related? See here: 

https://github.com/switchbrew/libnx/blob/aee9ba470687514a43273f8d31a76c52618cc0f8/nx/source/services/sfdnsres.c#L27

**Comment by yellows8** [comment]
Try `gai_strerror`.

**Comment by rsn8887** [comment]
Sorry the line mentioned in the last question with the suspicious strict was wrong it should be 
https://github.com/switchbrew/libnx/blob/aee9ba470687514a43273f8d31a76c52618cc0f8/nx/source/services/sfdnsres.c#L27

**Comment by yellows8** [comment]
Not sure if getaddrinfo ever worked (?).

"It looks to me as if ... The rough call sequence ...." It's just a service command + wrappers...

"switch-libcurl  ...  Is that maybe related?" no

"ALIGNED" *PACKED That's also unrelated.

**Comment by rsn8887** [comment]
Somewhat small example showing the problem. This should simply use DNS to turn hostname into IP numbers. Hardcoded hostname and port can be changed to anything. Tried with "www.google.com" "http", "172.217.2.36" "80" etc everything throws error 21:
```
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <netinet/in.h>

#include <switch.h>

//See also libnx hid.h.

int main(int argc, char **argv)
{
    consoleInit(NULL);

    char hostname[] = "content.openttd.org";
    char port[] = "3978";

    struct addrinfo hints, *res, *p;
    int status;
    char ipstr[INET6_ADDRSTRLEN];

    memset(&hints, 0, sizeof hints);
    hints.ai_family = AF_UNSPEC; // AF_INET or AF_INET6 to force version
    hints.ai_socktype = SOCK_STREAM;

    printf("Calling getaddrinfo hostname: "%s" port "%s":\n", hostname, port);

    if ((status = getaddrinfo(hostname, port, &hints, &res)) != 0) {
        printf("error getaddrinfo: %s, error nr: %d\n", gai_strerror(status), status);
    }

    printf("IP addresses for %s:\n", hostname);

    for(p = res;p != NULL; p = p->ai_next) {
        void *addr;
        char *ipver;

        // get the pointer to the address itself,
        // different fields in IPv4 and IPv6:
        if (p->ai_family == AF_INET) { // IPv4
            struct sockaddr_in *ipv4 = (struct sockaddr_in *)p->ai_addr;
            addr = &(ipv4->sin_addr);
            ipver = "IPv4";
        } else { // IPv6
            struct sockaddr_in6 *ipv6 = (struct sockaddr_in6 *)p->ai_addr;
            addr = &(ipv6->sin6_addr);
            ipver = "IPv6";
        }

        // convert the IP to a string and print it:
        inet_ntop(p->ai_family, addr, ipstr, sizeof ipstr);
        printf("  %s: %s\n", ipver, ipstr);
    }

    freeaddrinfo(res); // free the linked list

    // Main loop
    while(appletMainLoop())
    {
        //Scan all the inputs. This should be done once for each frame
        hidScanInput();
        //hidKeysDown returns information about which buttons have been just pressed (and they weren't in the previous frame)
        u64 kDown = hidKeysDown(CONTROLLER_P1_AUTO);
        if (kDown & KEY_PLUS) break; // break in order to return to hbmenu
        consoleUpdate(NULL);
    }

    consoleExit(NULL);
    return 0;
}
```

**Comment by rsn8887** [comment]
Maybe I am including the wrong headers? But everything compiles fine.

**Comment by rsn8887** [comment]
See here for the easy-to-use example:
https://github.com/rsn8887/switch-examples/tree/master/network/resolve-hostname

**Comment by rsn8887** [comment]
Here's the output from above program:
![](https://postimg.cc/2qv2nj10)

**Comment by yellows8** [comment]
socketInitialize/socketExit missing.

**Comment by rsn8887** [comment]
Perfect that was it! Now it works. :) Thank you so much!

**Comment by rsn8887** [comment]
I will update the example.
