### ISSUE TITLE
pmdmnt calls do not seem to work

### ISSUE THREAD

**Issue by ckurtz22** [switchbrew/libnx#257]
Right now I'm trying to use pmdmnt stuff to get application process ID. pmdmntGetApplicationPid seems to be returning garbage (right now it just put 0x4f434653 in it). pmdmntGetTitlePid seems to be returning the title ID it was passed in instead of the process ID for the title. I've made sure to run pmdmntInitialize, and I am checking the initialize for errors as well.

**Comment by ckurtz22** [comment]
Just tried pmdmntEnableDebugForApplication/TitleId, both of those are having similar issues.

**Comment by ckurtz22** [comment]
I'm using the latest master commit of libnx as of last night. Here is the code I was using for pmdmntGetTitlePid:

```     u64 pid = 0;
     Result rc;
     rc = pmdmntInitialize();
     if (R_FAILED(rc)) fatalSimple(rc);
     rc = pmdmntGetTitlePid(&pid, 0x0100e95004038000);
     if (R_FAILED(rc)) fatalSimple(rc);
     pmdmntExit();```
This would just set pid to 0x0x0100e95004038000. If I replaced pmdmntGetTitlePid with pmdmntGetApplicationPid then it would put what seemed to be random garbage in pid.

**Comment by yellows8** [comment]
What is this running from? A normal app?

**Comment by ckurtz22** [comment]
A sysmodule. Going to make a basic sysmodule and application that just uses this and test both to make sure

**Comment by yellows8** [comment]
If you're overriding __appInit you're probably missing this: https://github.com/switchbrew/libnx/blob/master/nx/source/runtime/init.c#L112

**Comment by ckurtz22** [comment]
Awesome, it works now!
