### ISSUE TITLE
Exception BadSvc on firmware 8.0.0

### ISSUE THREAD

**Issue by duckbill007** [switchbrew/libnx#267]
I am getting following exception only on 8.0.0:

```
Atmosphère Crash Report (v1.2):
Result:                          0x10A8 (2168-0008)

Process Info:
    Process Name:                hbloader
    Title ID:                    010000000000100d
    Process ID:                  0000000000000083
    Process Flags:               000000b3
    User Exception Address:      000000005f8ed000
Exception Info:
    Type:                        Bad Svc
    Address:                     0000000f991f31fc
    Svc Id:                      0x1d
```
On lower firmwares code works correct.
My code use std::conditional_variable am I right that this is broken right now?

**Comment by TuxSH** [comment]
8.0 kernel added crash-handling logic which  uses tls[0x100], which libnx also used.

Can you rebuild with latest _commit_ libnx and tell us if it works?

**Comment by fincs** [comment]
Relevant: https://github.com/switchbrew/libnx/commit/1c832bebd6735c108daa6ef2974dea5609b9d588

**Comment by duckbill007** [comment]
Yes. It seems, that latest commit fixes issue.
