### ISSUE TITLE
fsInitialize() crashes on 4.1.0

### ISSUE THREAD

**Issue by ckurtz22** [switchbrew/libnx#301]
Specifically, on this line https://github.com/switchbrew/libnx/blob/master/nx/source/services/fs.c#L15
(error code 2168-0002)

**Comment by yellows8** [comment]
what?

**Comment by ckurtz22** [comment]
I'm trying to run my sysmodule on 4.1.0 (that runs just fine on latest firmware), and it causes a fatal when loading. addr2line on the PC returns that line number.

**Comment by ckurtz22** [comment]
Oh forgot to mention this is in a sysmodule.

**Comment by yellows8** [comment]
Not really enough info - where's the source for this sysmodule? Can you gist the reports for this?

**Comment by ckurtz22** [comment]
https://github.com/ckurtz22/SplitNX/blob/master/source/main.cpp#L44 here's the code. I'm not sure what else you want, there aren't any reports? It just fatals with 2168-0002...

**Comment by yellows8** [comment]
crash_reports / fatal_reports

**Comment by SciresM** [comment]
2168-0002 is creport. That error can only show up if a crash report has been saved.

**Comment by ckurtz22** [comment]
Ah, they were in crash_reports. Assumed since it was fatal screen they'd go into fatal_reports... one second...

**Comment by ckurtz22** [comment]
https://gist.github.com/ckurtz22/4cc907bc70dfd2441d10e95f047e9b71

**Comment by yellows8** [comment]
Can you upload the.elf?

**Comment by SciresM** [comment]
Do you mean for your code to validate those Result codes? Not sure why you don't check results from init code lol

**Comment by ckurtz22** [comment]
https://drive.google.com/open?id=1n-iTujSWDSVt5RybNBj694Ik6j9929FD 
Here is the elf. I pushed a new commit to my repo and updated the gist with a different crash report because I had rebuilt the project after commenting out more twili stuff in case that was the issue.

**Comment by ckurtz22** [comment]
Nevermind. I fixed it. I had cut down my main_thread_stack_size super low a while ago while trying to get it to be able to run alongside other sysmodules fine. It worked fine at the size I set, and I forgot about that. I guess something is different about 4.1.0 where you can't have a stack_size that low, cause when I moved it back to the default 0x4000 it worked fine.
