### ISSUE TITLE
mkdir segfaults when creating directories with colons

### ISSUE THREAD

**Issue by crc-32** [switchbrew/libnx#307]
Creating directories via mkdir with colons included in the path results in an 0x4A8 fatal.

**Comment by yellows8** [comment]
Not enough info.

**Comment by NexoDevelopment** [comment]
Creating directories via mkdir with colons included in the path results in a data abort

**Comment by crc-32** [comment]
Moved to https://github.com/devkitPro/newlib/issues/14
