### ISSUE TITLE
appletRequestLaunchApplication is broken

### ISSUE THREAD

**Issue by WerWolv** [switchbrew/libnx#323]
Calling `appletRequestLaunchApplication` with any titleID and NULL for the AppletStorage results in a popup stating `Could not start the Software` and the home menu to show up. I do own all the games on my system and they start up properly when launching them from the home menu.

**Comment by yellows8** [comment]
And with a TID for a title that doesn't exist? What sysver?

FWIW using `appletExecuteProgram` with an invalid programIndex has a similar result (which would then use a title that doesn't exist): https://switchbrew.org/wiki/Applet_Manager_services#ProgramSpecifyKind

**Comment by WerWolv** [comment]
Same with a titleID that doesn't exist.
System version is 8.1.0.
I tried with both setting `__nx_applet_type` to ether Application and LibraryApplet and also by launching the homebrew though the Album and through an Application override. Same result every time.

**Comment by yellows8** [comment]
Try from a dedicated app with a hard-coded titleID?

**Comment by WerWolv** [comment]
Dedicated app? How would I do that?

**Comment by yellows8** [comment]
As in a nro app.

**Comment by WerWolv** [comment]
Nope, doesn't seem to work either...

**Comment by WerWolv** [comment]
It works now. Not sure what I did wrong exactly though
