### ISSUE TITLE
openssl port for https in curl?

### ISSUE THREAD

**Issue by darkxex** [switchbrew/libnx#327]
Is it possible to opensl port or something that allows using curl with https on switch?

**Comment by yellows8** [comment]
HTTPS with curl can already be used via mbedtls.

**Comment by darkxex** [comment]
My friend, it would be possible to publish a simple example code, I am half silly.

**Comment by yellows8** [comment]
Probably should be added at some point...

**Comment by darkxex** [comment]
thank you friend, but do you have any app in which the curl with https and mbedtls has been used or do you know someone who has made one to look at your code?

**Comment by yellows8** [comment]
None that will be linked here.

**Comment by darkxex** [comment]
Thanks friend, I will be impatient waiting for the example of ssl.

**Comment by fincs** [comment]
Closing due to offtopic (this is not the right place to ask about portlibs).
