### ISSUE TITLE
Can't install on Ubuntu 19.04

### ISSUE THREAD

**Issue by melsbacksfriend** [switchbrew/libnx#328]
This is the error I get when running make.  
newlib.c
aarch64-none-elf-gcc -MMD -MP -MF /home/melsbacksfriend/Downloads/libnx-2.5.0/nx/release/newlib.d -g -Wall -Werror -ffunction-sections -fdata-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIC -ftls-model=local-exec -DNDEBUG=1 -O2 -I/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/include -I/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/external/bsd/include  -I. -iquote /home/melsbacksfriend/Downloads/libnx-2.5.0/nx/include/switch/ -DSWITCH -c /home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c -o newlib.o 
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c:97:27: error: unknown type name '_COND_T'; did you mean '_LOCK_T'?
 int __syscall_cond_signal(_COND_T *cond)
                           ^~~~~~~
                           _LOCK_T
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c:102:30: error: unknown type name '_COND_T'; did you mean '_LOCK_T'?
 int __syscall_cond_broadcast(_COND_T *cond)
                              ^~~~~~~
                              _LOCK_T
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c:107:25: error: unknown type name '_COND_T'; did you mean '_LOCK_T'?
 int __syscall_cond_wait(_COND_T *cond, _LOCK_T *lock, uint64_t timeout_ns)
                         ^~~~~~~
                         _LOCK_T
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c:112:35: error: unknown type name '_COND_T'; did you mean '_LOCK_T'?
 int __syscall_cond_wait_recursive(_COND_T *cond, _LOCK_RECURSIVE_T *lock, uint64_t timeout_ns)
                                   ^~~~~~~
                                   _LOCK_T
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c: In function '__syscall_nanosleep':
/home/melsbacksfriend/Downloads/libnx-2.5.0/nx/source/runtime/newlib.c:420:20: error: implicit declaration of function 'timespec2nsec'; did you mean 'timespec2bintime'? [-Werror=implicit-function-declaration]
     svcSleepThread(timespec2nsec(req));
                    ^~~~~~~~~~~~~
                    timespec2bintime
cc1: all warnings being treated as errors
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:19: newlib.o] Error 1
make: *** [Makefile:124: lib/libnx.a] Error 2

**Comment by fincs** [comment]
Please cease whatever you are doing, and head over to the page for [devkitPro pacman](https://devkitpro.org/wiki/devkitPro_pacman). It looks like you need to `sudo dkp-pacman -Syu` in order to update your toolchain (devkitA64) installation. You are also strongly advised against trying to build libnx on your own; and instead please use the pre-built stable package we provide through pacman.

**Comment by melsbacksfriend** [comment]
Thank you!
