### ISSUE TITLE
usbHsEpClose filling the EpSession for the length of IfSession

### ISSUE THREAD

**Issue by cathery** [switchbrew/libnx#337]
[Line reference](https://github.com/switchbrew/libnx/blob/5f5d4c9785e298b551768a0ada258073ddafb2e0/nx/source/services/usbhs.c#L343)

I don't think this is intentional. My code works fine with singular objects using EpSession, but as soon as arrays come into play, everything crashes. (probably due to the size of EpSession being changed? is that a thing?) After changing the type in `sizeof()` to `UsbHsClientEpSession`, everything works fine again.

**Comment by yellows8** [comment]
Ugh, thanks.
