### ISSUE TITLE
socketInitializeDefault sometimes never returns

### ISSUE THREAD

**Issue by friedkeenan** [switchbrew/libnx#346]
This issue only occurs on master, not the latest release.

[Here](https://gist.github.com/friedkeenan/158daa5578fbe20796da450cf8084c5f) is an example to show the issue. It calls `socketInitializeDefault`, and then when you repeatedly press plus, which does `envSetNextLoad` on itself and then exits, eventually `socketInitializeDefault` will never return, and the console will require a reboot to get out of it.

**Comment by yellows8** [comment]
Does that happen with normal hbmenu-return + app launch?

**Comment by friedkeenan** [comment]
Well, this is strange. Doing it that way I eventually get a hang that requires a reboot, but it doesn't print `Before socketInitializeDefault`

**Comment by fincs** [comment]
See commit above. Thank you very much for making us catch this bug :)

**Comment by friedkeenan** [comment]
Thank you for fixing it :)
