### ISSUE TITLE
Request for Adding Rumble Support. 

### ISSUE THREAD

**Issue by Ntemis** [switchbrew/libnx#347]
Hello,
Since now with cathery's(https://github.com/cathery/sys-con) excellent sys-con we can add 4 Xbox360 Wireless controllers and other peripherals like DS3/DS4 Wii-U Pro controller etc
we badly need rumble support to be implemented to make it a whole.
We beg for Rumble support when and if possible!
Best regards

**Comment by fincs** [comment]
Rumble is technically already supported, but it doesn't work properly due to a bug we haven't been able to debug or fix yet.

**Comment by yellows8** [comment]
@fincs hiddbg, not hid.

And that would be system-side, not libnx.

**Comment by yellows8** [comment]
Don't think the system supports this for virtual controllers (?).
