### ISSUE TITLE
Broken timezone handling with certain timezones.

### ISSUE THREAD

**Issue by cucholix** [switchbrew/libnx#353]
Using atmosphere 0.10.1, FW 9.1.0.
The time displayed in the upper right corner in hbmenu is off by 3 hours, example: if the time in system menu is 15:00, hbmenu will display 18:00. My timezone is Santiago (UTC -3:00).

Other people are experiencing the same issue https://gbatemp.net/threads/how-to-change-hbmenu-to-the-correct-time-zone-as-switch.553221/

**Comment by yellows8** [comment]
(for reference https://github.com/Atmosphere-NX/Atmosphere/issues/756)

**Comment by i4s33u** [comment]
I have this issue, too. My timezone in hbmenu seems to be locked at GMT +0

**Comment by evertonstz** [comment]
Was this ever fixed? I still face this problem to this day :/

**Comment by yellows8** [comment]
Yes hence the above commit... No stable-release which includes it yet though.

**Comment by evertonstz** [comment]
> 
> 
> Yes hence the above commit... No stable-release which includes it yet though.

Yes, I didn't noticed it, this commit was like 9 days after the latest release xD
