### ISSUE TITLE
[Question] timeSetCurrentTime() fails to set system time

### ISSUE THREAD

**Issue by Androidown** [switchbrew/libnx#357]
Please kindly tell me if the  function 

> timeSetCurrentTime(TimeType type, u64 timestamp) 

is used to set system time for NS?
I've tried all possible TimeType with timestamp equals to 1573776600. But the result code is always 1.
Am doing anything wrong or missing anything ?
Tested on Reinx with firmware 8.1.0.

**Comment by yellows8** [comment]
Set __nx_time_service_type, that's not available with the default (User).
