### ISSUE TITLE
usb:hs doesn't seem to be properly implemented

### ISSUE THREAD

**Issue by XorTroll** [switchbrew/libnx#359]
I was playing around with usb:hs, and since posting buffers would always fail with result 0x3228C, I decided to do some testings with https://github.com/Stary2001/nx-fatdrive-cpp, which worked fine with older libnx versions (I have used this project several times), but none of my FAT32 USBs worked, all hanging for the same reason.
This service seems to be a little bit messy, considering changes between versions, but I can guarantee that all this would work fine with older libnx versions.

**Comment by yellows8** [comment]
Make sure you're using the right endpoints, see releases changelog & the example (older releases used to have input/output endpoints swapped in UsbHsInterfaceInfo).

**Comment by XorTroll** [comment]
I thought that the swap of endpoints was handled internally by libnx, so the sources should be updated swapping the endpoints...?

**Comment by XorTroll** [comment]
Swapping them works fine :P

**Comment by yellows8** [comment]
If you're for example using `input_endpoint_descs` and actually wanted OUTPUT, change it to output.

**Comment by XorTroll** [comment]
I did that, just that it feels a little bit weird :P

**Comment by yellows8** [comment]
https://github.com/switchbrew/libnx/releases/tag/v3.0.0

Apps using that struct previously had to work-around this by using the wrong endpoint field, with this release apps have to revert it to the proper endpoint field.
