### ISSUE TITLE
LibnxError_InitFail_Time when using __nx_time_service_type = TimeServiceType_System on 8.0.1

### ISSUE THREAD

**Issue by 3096** [switchbrew/libnx#361]
Atmosphère Fatal Report (v1.0):
Result:                          0x4D59 (2345-0038)
Firmware:                        8.0.1 (Atmosphère 0.10.1-master-a2d2b1b3)

**Comment by yellows8** [comment]
More context?

**Comment by 3096** [comment]
timeInitialize() fails I assume, as when I try to use `__nx_time_service_type = TimeServiceType_System` the system fatals on launching the homebrew.

**Comment by yellows8** [comment]
NRO launched with latest hbloader?

**Comment by 3096** [comment]
Yeah. 
hbloader v2.3.0
libnx v3.0.0

**Comment by 3096** [comment]
For context,
https://github.com/switchbrew/libnx/blob/1bb1aef2f7ffbeb86ddce97e72f42ff4719da8e8/nx/include/switch/services/time.h#L12-L19
`TimeServiceType_User` and `TimeServiceType_Menu` seems to be fine
`TimeServiceType_System` fails for some reason, even tho it doesn't say it needs a certain firmware or anything
`TimeServiceType_Repair` and `TimeServiceType_SystemUser` are stated for 9.0.0+

**Comment by yellows8** [comment]
This worked fine on 9.x IIRC...

Do you have any extra sysmodules running perhaps?

**Comment by 3096** [comment]
Hmmm. Grabbed a clean SD card and it worked fine. Could this be caused by another process? Is it that the service can't be used by more than one?

**Comment by yellows8** [comment]
https://switchbrew.org/wiki/PSC_services#time:su.2C_time:s

Remove any extra sysmodules not included with vanilla AMS from `atmosphere/contents/`.

**Comment by 3096** [comment]
Thx a lot for solving my problem! Turns out that one sys module causing problem needed rebuild with libnx 3.0
Worked fine after rebuilding
