### ISSUE TITLE
Auth applet fatal on 9.1.0

### ISSUE THREAD

**Issue by HookedBehemoth** [switchbrew/libnx#365]
Calling pctlauth* on 9.1.0 will fatal sm with 0x1015 Permission denied.

**Comment by yellows8** [comment]
Make sure Parental Controls are actually enabled, and nothing in /atmosphere/contents/ which might modify anything related.

Gist for the report?

**Comment by HookedBehemoth** [comment]
https://gist.githubusercontent.com/HookedBehemoth/0d7b5b31f00229f273d36594784ac344/raw/514717e72c2288ae5fa328852e3ee329d9fe9728/9.1.0%2520pctl%2520auth%2520fatal

Parental Control enabled, nothing in /atmosphere/contents/ besides stock atmosphere stuff.
Code worked before 9.1.0.
Sb else experienced the same issue with his application (worked before, fatals now).

**Comment by yellows8** [comment]
It works here - are you really using the latest vanilla AMS stable release?

**Comment by HookedBehemoth** [comment]
Tried it again with the latest Atmosphère release. Same result.
I usually use hekate but the same thing happened with fusee-primary.
@WerWolv experienced the same behaviour.

**Comment by HookedBehemoth** [comment]
https://gist.githubusercontent.com/HookedBehemoth/9ba8f1c78fb12456ced0b61b4c0d708d/raw/dafc705b528561fe8bdb78dcb5bb62d586cabdb2/pctl
Works on anything below 9.1.0 but fatals on 9.1.0.

**Comment by yellows8** [comment]
Same thing with switch-examples/applet/libapplets/pctlauth right?

**Comment by HookedBehemoth** [comment]
That works and what make it work again is move pctlExit before pctlauthShow.
Seems like they decreased the ref count of pctl.
