### ISSUE TITLE
lbl.c _lblCmdNoInOutBool wrong comparison

### ISSUE THREAD

**Issue by RetroGamer74** [switchbrew/libnx#367]
Hi this is a bug fix report.
File: lbl.c
Line: 36
Current: if (R_SUCCEEDED(rc) && out) *out = tmpout & 1;
Fix: if (R_SUCCEEDED(rc)) *out = tmpout != 0;

Expected behaviour should get the brightness enabled/disabled state.
Current line is not providing me the right status.
With the suggested fix it works ok.

Thanks.

**Comment by yellows8** [comment]
What are you doing with lbl / code you're using? Should use applet* normally...

**Comment by RetroGamer74** [comment]
Replacing switch overlay.

**Comment by yellows8** [comment]
"code you're using?"

**Comment by yellows8** [comment]
`& 1` was already correct, same thing is done elsewhere. Tested using lblIsAutoBrightnessControlEnabled myself under an Application, worked fine.
