### ISSUE TITLE
Is it possible to add <sys/uio.h>?

### ISSUE THREAD

**Issue by glebm** [switchbrew/libnx#370]
`readv` and friends from `<sys/uio.h>` are used by DevilutionX for networking (via [asio](https://github.com/chriskohlhoff/asio/)).

DevilutionX currently does not compile with network support because the `<sys/uio.h>` is missing. Would it be possible to add it here?

Then we'd be able to play Diablo in cross-platform multiplayer from the Switch!

/cc @AJenbo @rsn8887

**Comment by glebm** [comment]
After looking into it a bit further, I realize I should have opened this request in a different repo. Is https://github.com/reswitched/newlib the right place for such things?

**Comment by rsn8887** [comment]
sys/un.h is also missing.

**Comment by fincs** [comment]
This repository is indeed the wrong one to request this feature on. Also, "reswitched/newlib" has absolutely nothing to do with devkitPro. The correct newlib we're using in devkitPro toolchains (devkitA64 in our case) is this one: https://github.com/devkitPro/newlib

With that said, there's kind of a limit to the amount of POSIX compatible interfaces we're able to provide, where we really have to see if adding little known interfaces like this one is worth the cost of implementing, supporting and maintaining them.
