### ISSUE TITLE
Warnings in pmbmInitialize and pmbmExit

### ISSUE THREAD

**Issue by crudelios** [switchbrew/libnx#371]
In:

https://github.com/switchbrew/libnx/blob/68d6260d72e56e8af16ae7f3f2ce74026abe0f2a/nx/include/switch/services/pm.h#L87-L91

Both functions generate a `function declaration isn't a prototype [-Wstrict-prototypes]` warning when using gcc.

`void` needs to be added as a "parameter" to both functions to fix the warning.

I know this is small, but it's also an easy fix.

**Comment by fincs** [comment]
Good catch.
