### ISSUE TITLE
Capture button reported as held when left joystick moved

### ISSUE THREAD

**Issue by ndeadly** [switchbrew/libnx#379]
When the dy value for the left joystick is (approx.) < `JOYSTICK_MIN/2` the value returned by `hidKeysDown`/`hidKeysHeld` indicates the capture button is being held.

The following code demonstrates the issue (Tested on 5.0.1)

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <switch.h>

int main(int argc, char* argv[])
{

    consoleInit(NULL);

    while (appletMainLoop())
    {
        hidScanInput();

        u64 kDown = hidKeysDown(CONTROLLER_P1_AUTO);
        u64 kheld = hidKeysHeld(CONTROLLER_P1_AUTO);

        if (kDown & KEY_PLUS)
            break;

        consoleClear();

        JoystickPosition left_stick;
        JoystickPosition right_stick;
        hidJoystickRead(&left_stick, CONTROLLER_P1_AUTO, JOYSTICK_LEFT);
        hidJoystickRead(&right_stick, CONTROLLER_P1_AUTO, JOYSTICK_RIGHT);
        printf("Lx: %+06d Ly: %+06d\nRx: %+06d Ry: %+06d\n", left_stick.dx, left_stick.dy, right_stick.dx, right_stick.dy);
        printf("capture: %d\n", (kheld & KEY_CAPTURE) > 0);

        consoleUpdate(NULL);
    }

    consoleExit(NULL);
    return 0;
}
```

**Comment by yellows8** [comment]
From docs: `, only available for use with HiddbgHdlsState::buttons.` Do not use KEY_HOME/KEY_CAPTURE outside of hiddbg.

**Comment by ndeadly** [comment]
Ah ok, missed that one. So there's no way to read the state of home/capture, only write via virtual controllers?

**Comment by yellows8** [comment]
ATM, no.

**Comment by yellows8** [comment]
What's the use-case?(maybe check applet.h / elsewhere)

**Comment by ndeadly** [comment]
I'm writing an application for managing foreign Bluetooth controllers. Looking to add a diagnostic feature for testing button function and verifying remappings
