### ISSUE TITLE
how can I create a soft keyboard for inputing Chinese or Korean characters

### ISSUE THREAD

**Issue by Polytoo** [switchbrew/libnx#386]
The default soft keyboard can't choose Chinese or Korean language.
But the official soft keyboard can works well.

**Comment by yellows8** [comment]
swkbdConfigSetType(..., SwkbdType_Normal)

**Comment by Polytoo** [comment]
> swkbdConfigSetType(..., SwkbdType_Normal)

Thank you for your quick reply.
I just try your code.
There are some major language can be choosed, Including Japenese.
But still without Chinese and Korean.

**Comment by yellows8** [comment]
System-language probably needs set to those - what's your system-language?

**Comment by Polytoo** [comment]
I am using Chinese Simplified System-language.
I am using the example soft keyboard code to modify.
I will try Chinese Traditional language to see what will happen.

**Comment by Polytoo** [comment]
OK, I try some different params and figured out the answer :)

1 = SwkbdType_Normal
2 = Number keyboard
3 = QWERT keyboard
4 = Only Latin like languages. (without Japenese compare setting to SwkbdType_Normal)
5 = Only Chinese simplified
6 =  Only Chinese traditional
7 = Only Korean
8 = Include all languages keyboards ^0^
9 = The same as 8
10 >= The same as 1

I didn't try any further.
So, set to 8, would be a good idea.

**Comment by yellows8** [comment]
Uh did you mean 0-based not 1-based? <https://github.com/switchbrew/libnx/blob/master/nx/include/switch/applets/swkbd.h#L21>

**Comment by Polytoo** [comment]
Oh,I have just post a PR. 

    SwkbdType_Normal    = 0,  ///< Normal keyboard.
    SwkbdType_NumPad    = 1,  ///< Number pad. 
    SwkbdType_QWERTY    = 2,  ///< QWERTY (and variants) keyboard only.
    SwkbdType_Unkown    = 3,  ///< The same as SwkbdType_Normal keyboard.
    SwkbdType_Latin     = 4,  ///< Latin like languages keyboard only.
    SwkbdType_CHS       = 5,  ///< Chinese Simplifid keyboard only.
    SwkbdType_CHT       = 6,  ///< Chinese Simplifid keyboard only.
    SwkbdType_Korean    = 7,  ///< Korean keyboard only.
    SwkbdType_All       = 8,  ///< All language keyboards.

**Comment by yellows8** [comment]
#387
