### ISSUE TITLE
Can't compile code

### ISSUE THREAD

**Issue by Gabz0r785897** [switchbrew/libnx#395]
This is based on the chip8 emulator tutorial on *(link removed)*

$ make
linking c8-master.elf
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/9.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/libnx/lib\libnx.a(switch_crt0.o): in function `bss_loop':
/home/fincs/pacman-packages/libnx/src/libnx-3.1.0/nx/source/runtime/switch_crt0.s:72: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /c/users/admin/downloads/c8-master/c8-master/c8-master.elf] Error 1
make: *** [Makefile:165: build] Error 2

Apparently there is something wrong with my makefile but it's basically a drag and drop from the application template in the switch homebrew examples, aside from adding sdl2 to the libraries.
I can compile the original example completely fine however. This can't be a problem with my code as it originates in the makefile, before my code is acknowledged.

**Comment by fincs** [comment]
The "tutorial" you linked to is really out of date, and teaches bad programming practices.

We provide an actual [SDL2 example](https://github.com/switchbrew/switch-examples/blob/master/graphics/sdl2/sdl2-simple), with a Makefile you can copy to your project instead. Note how the recommended way of linking to SDL is way simpler:

    LIBS	:=	`sdl2-config --libs`

**Comment by Gabz0r785897** [comment]
> The "tutorial" you linked to is really out of date, and teaches bad programming practices.
> 
> We provide an actual [SDL2 example](https://github.com/switchbrew/switch-examples/blob/master/graphics/sdl2/sdl2-simple), with a Makefile you can copy to your project instead. Note how the recommended way of linking to SDL is way simpler:
> 
> ```
> LIBS	:=	`sdl2-config --libs`
> ```

I'm still having problems with your makefile.
linking c8-master.elf
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/9.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/libnx/lib\libnx.a(switch_crt0.o): in function `bss_loop':
/home/fincs/pacman-packages/libnx/src/libnx-3.1.0/nx/source/runtime/switch_crt0.s:72: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /c/users/admin/downloads/c8-master/c8-master/c8-master.elf] Error 1
make: *** [Makefile:165: build] Error 2

Any reason why is this happening???

**Comment by fincs** [comment]
It looks like you have no main function.

**Comment by Gabz0r785897** [comment]
I am sure it uses SDL2.

**Comment by fincs** [comment]
> Edit: I'm sorry, I edited the make file a bit, sorry for the confusion. It said that the sdl2 config libs weren't recognized and neither was --libs originally with no edits to the makefile

Make sure you have the packages `switch-pkg-config` and `switch-sdl2` installed.

Also, this is technically not a libnx issue. You might be better off asking for help here: https://devkitpro.org/viewforum.php?f=42

**Comment by Gabz0r785897** [comment]
$ make
linking c8-master.elf
c:/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/9.2.0/../../../../aarch64-none-elf/bin/ld.exe: C:/devkitPro/libnx/lib\libnx.a(switch_crt0.o): in function `bss_loop':
**/home/fincs/pacman-packages/libnx/src/libnx-3.1.0/nx/source/runtime/switch_crt0.s:72: undefined reference to `main'**
collect2.exe: error: ld returned 1 exit status
**make[1]: *** [/opt/devkitpro/libnx/switch_rules:80: /c/users/admin/downloads/c8-master/c8-master/c8-master.elf] Error 1**
make: *** [Makefile:165: build] Error 2

Still have a problem. I bolded the parts that led me to believe it's libnx. And I have installed switch-pkg-config with the same error.

**Comment by WinterMute** [comment]
Your problem has nothing to do with libnx. The linker can't find a main function. Ask for help on https://devkitpro.org/viewforum.php?f=42 this is not a libnx issue.
