### ISSUE TITLE
allow libnx to be used as a submodule

### ISSUE THREAD

**Issue by jfmherokiller** [switchbrew/libnx#398]
Would somone be willing to edit libnx to allow it to be used as a git submodule?

This would require editing switch_rules and switch.specs to work possibly without libnx located under the devkitpro environment variable

for the specs file refer here https://gcc.gnu.org/onlinedocs/gcc/Spec-Files.html

i think it would be doable with usage of `if-exists-else` 

for make some if statments will be needed

**Comment by fincs** [comment]
No. libnx must not be used as a sysmodule and we will not consider allowing it. Users must use stable libnx releases installed by dkp-pacman.

**Comment by WinterMute** [comment]
And please don't attempt to create and maintain build infrastructure independently of devkitPro. It causes massive support headaches when people use infrastructure we didn't create that turns out to be broken because nobody consulted anyone who knows how the tools are supposed to work.
