### ISSUE TITLE
pread/pwrite?

### ISSUE THREAD

**Issue by leo60228** [switchbrew/libnx#403]
Seeking are an abstraction from libnx, right? So this should be easy?

**Comment by leo60228** [comment]
They already exist in newlib as wrappers over lseek/read/write, but they aren't getting built and I can't figure out why...

**Comment by fincs** [comment]
pread/pwrite and other POSIX/libc functions aren't the responsibility of libnx. They fall under newlib's domain, as you have later pointed out, therefore I'm closing this issue.

I don't know where you've seen those "wrappers" in newlib, we certainly don't have those functions at all. pwrite/pread seem to be intended to be used for thread safe file operations, and implementing them with read/write/lseek would defeat their purpose.

**Comment by leo60228** [comment]
https://github.com/devkitPro/newlib/blob/devkitA64/newlib/libc/unix/pread.c

**Comment by WinterMute** [comment]
> https://github.com/devkitPro/newlib/blob/devkitA64/newlib/libc/unix/pread.c

This is for unix hosts, it's not relevant to us. This issue isn't relevant to libnx.

**Comment by leo60228** [comment]
I'm not sure where to request features in newlib, and as far as I can tell devkitA64's newlib and libnx are very closely related, so I opened it here. Where should I put it?
