### ISSUE TITLE
hidsys.h -> HidcfgButtonConfig_Minus and HidcfgButtonConfig_Plus seem swap around

### ISSUE THREAD

**Issue by hxhieu** [switchbrew/libnx#415]
Hi,

`SDL_Event` on `SDL_JOYBUTTONDOWN` is saying (+) is 10 and (-) is 11 while all other buttons are fine.

I am not sure it's the libnx issue or switch_sdl issue?

Thanks.

**Comment by yellows8** [comment]
The HidcfgButtonConfig enum for those is fine, just checked it again.

**Comment by yellows8** [comment]
HidcfgButtonConfig is unrelated to any enum in SDL2 (or elsewhere).
