### ISSUE TITLE
Edge case in romfs_dev when calling stat("romfs:/")

### ISSUE THREAD

**Issue by Stary2001** [switchbrew/libnx#417]
stat("romfs:/") fails with EILSEQ
as far as I can tell:
* navigateToDir is called with "romfs:/"
* the very start has a special case for `if (**pPath == '/')` which sets to root + advances the string pointer past the slash
* which means the middle `while (**pPath)` never runs as it's at the null terminator already
* so `if (!isDir && !**pPath)  return EILSEQ;` is hit
I don't know enough about the rest of the code here to propose a fix, so reporting an issue instead.

**Comment by fincs** [comment]
Fixed by db795f4.
