### ISSUE TITLE
Opening webapplet from applet mode freezes and eventually crashes

### ISSUE THREAD

**Issue by HookedBehemoth** [switchbrew/libnx#477]
When opening the web applet from applet override it freezes for about 30 seconds and eventually crashes.
[Crash report](https://github.com/switchbrew/libnx/files/4705661/01590798361_010000000000100a.log)

Tested on FW 10.0.x and 4.0.1 with various reserved RAM sizes with the [web applet example.](https://github.com/switchbrew/switch-examples/tree/master/applet/libapplets/web)

At 0x16000000 it opens but fatals on exit. No crash report is generated. [Fatal report](https://github.com/switchbrew/libnx/files/4705665/01590796465_010000000000100a.log)
Anything I tested below that froze. Above that [hbmenu wasn't useable.](https://user-images.githubusercontent.com/22580720/83329358-521be300-a289-11ea-9ff6-f152dd2a9b15.jpg)

**Comment by yellows8** [comment]
try: `applet_heap_size = u64!0xf200000`

**Comment by HookedBehemoth** [comment]
Freeze and crash
Identical to the crash at default size with the same break address.

**Comment by yellows8** [comment]
Webapplet is failing to allocate enough heap. Same thing with `applet_heap_size = u64!0x4000000`

This isn't really libnx related (AMS repo would be more relevant(?)), so closing.
