### ISSUE TITLE
SL/SR doesn't work when emulating a joy con with hiddbg

### ISSUE THREAD

**Issue by PaskaPinishkes** [switchbrew/libnx#489]
When I try to emulate a joycon (JoyLeft2, JoyRight1, JoyLeft4, JoyRight5), SL and SR buttons don't work on my sysmodule
When SL or SR buttons are pressed and any other button is pressed (e.g A button), the A button is detected but the SL or SR buttons are not
I have tried KEY_SL_LEFT, KEY_SL_RIGHT, KEY_SL and the derivatives for the SR button
While I tested my sysmodule in 10.0.4, I also remember seeing this issue in 9.X

**Comment by yellows8** [comment]
Try it with the hdls example? Did you try disabling shmem-mitm?

**Comment by PaskaPinishkes** [comment]
Hello, from what I have seen in the hdls example, the SL input is registered, but Horizon OS doesn't recognize it as an input
This makes games such as 1-2 Switch to be unplayable when emulating a joy con with hiddbg on a sysmodule.
I never enabled shmem-mitm

**Comment by yellows8** [comment]
So SL does show up when button-A is pressed in the example?

**Comment by PaskaPinishkes** [comment]
I added these lines of code
`if (hidKeysHeld(conID) & KEY_DUP)
 state.buttons |= KEY_SL_LEFT;
            
if (state.buttons & KEY_SL)
 printf("SL Pressed! BUTTONS: %lu", state.buttons);`
SL is pressed and the printf function is executed, but in my sysmodule when I make my virtual hiddbg controller press KEY_SL_LEFT, Horizon OS doesn't recognize it

**Comment by yellows8** [comment]
Meant the output from hidKeysHeld().

**Comment by PaskaPinishkes** [comment]
oh
Just checked that out, SL and SR are not detected from my controllers, it just says buttons = 0x1 (I suppose it says that instead of 0x0 because I pressed A to print that)

**Comment by PaskaPinishkes** [comment]
tested with sideways joycon, the SL and SR buttons don't output either

**Comment by yellows8** [comment]
https://switchbrew.org/wiki/HID_services#HdlsState

Bit20-27 are masked out by HOS, which includes the SL/SR buttons.
