### ISSUE TITLE
could someone tell me how to init and read ring-con data via hid command ?

### ISSUE THREAD

**Issue by lyonlui** [switchbrew/libnx#494]
I am working on a project that port joy-con to [Android,](https://github.com/lyonlui/BetterJoy_for_Android) But i can not find any information about command to init external device (eg: ring-con fof ring fit adventure) and read information.

**Comment by yellows8** [comment]
That layer isn't doc'd AFAIK, someone would have to RE that (service-layer is doc'd though, see libnx ringcon impl / <https://switchbrew.org/wiki/Ring-Con>).

**Comment by lyonlui** [comment]
> ringcon
Thanks for relpy.
You guys should shutdown php debug(page show php debug info) !!! 
I already read this link before you send it to me, But i do not think this is HID commad.
