### ISSUE TITLE
libnx 4.0 time bug

### ISSUE THREAD

**Issue by DejaDegausser** [switchbrew/libnx#522]
Apps built with versions 4.0 of libnx consistently read the time on my system incorrectly across all clocks. Using a test app built just to show the time for testing, it reads that the date is July 31st 2605 across NetworkSystemClock, UserSystemClock and LocalSystemClock. However the date on my console is displayed correctly, and building the same app with version 3.0 of libnx causes it to show the exact time and date my console does. This becomes an issue with apps that use SSL because it causes SSL to fail due to the date being dead incorrectly. 
![2021010909491700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/77202273/104096135-4a311200-5260-11eb-9615-fbf8661deeb5.jpg)
![2021010909492400-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/77202273/104096140-4f8e5c80-5260-11eb-99cb-5097d37a67c3.jpg)

I have tried:
Using a separate NAND, despite having first discovered the issue on an emuNAND it also affected my sysNAND
Updating atmosphere/hekate to the latest versions
Maintenance mode + reinitializing the system
Changing the system time manually
The only thing that fixes the issue is using older versions of the apps

**Comment by yellows8** [comment]
And libnx v3.2.0, which was when time-service was last changed?

**Comment by yellows8** [comment]
Can't repro with latest libnx. What app is this?

**Comment by arch-box** [comment]
> 
> 
> Can't repro with latest libnx. What app is this?

https://github.com/arch-box/NX-ntpc/releases/tag/1.0.1

**Comment by DejaDegausser** [comment]
The version compiled with v3.2.0 does not show the correct date/time

**Comment by yellows8** [comment]
Still can't repro with that app (built from source). What system-version?

**Comment by DejaDegausser** [comment]
I tried with both 10.1.0 and 9.2.0 which were the two versions I had on hand. I'm aware the issue only seems to affect my console and I have no idea why, it just showed up one day. The same apps that don't work for me now used to work perfectly a week ago before my console died.

**Comment by WinterMute** [comment]
What do you mean by "before your console died"?

**Comment by DejaDegausser** [comment]
I was referring to in my last comment when I said my console was dead for a week or two (as in out of battery). Before that point all the apps worked properly, afterwards any app build with recent versions of libnx have this issue. I don't know if the events are directly related but I figured its worth mentioning.

**Comment by arch-box** [comment]
could this be caused by an error in __libnx_init_time, where it sets up boot time variables:

https://github.com/switchbrew/libnx/blob/9e52e55177e9385c5502f20cbd139c64bbe5ee2c/nx/source/runtime/newlib.c#L300

__boottime = UINT64_MAX is 18446744073709551615, right?

That's July 21, 2554 4:34:33.709 PM counting from unix epoch. User is getting July 31, 2605 which is 51 years + 10 days added to it. We are 51 years, 10 days from unix epoch. It appears that libnx 3.2 onward is counting the date on this user's Switch from UINT64_MAX instead of from the unix epoch and resulting in this very large date.

**Comment by yellows8** [comment]
https://github.com/arch-box/NX-ntpc/blob/master/source/main.c#L152 Print the value of time() output and errno here?

**Comment by arch-box** [comment]
> 
> 
> https://github.com/arch-box/NX-ntpc/blob/master/source/main.c#L152 Print the value of time() output and errno here?

User reported that time() outputs 20057063041 and rc returns 0, printing the __libnx_rc result from here:

```c
    Result rc =  timeGetCurrentTime(__nx_time_type, &__boottime);
    __libnx_rc = rc;
    if (R_FAILED(rc) && __nx_time_type != TimeType_Default) rc =  timeGetCurrentTime(TimeType_Default, &__boottime);
    if (R_FAILED(rc)) {
        __boottime = UINT64_MAX;
    } else {
        __bootticks = armGetSystemTick();
    }
```

> And libnx v3.2.0, which was when time-service was last changed?

I compiled using 3.2.0 btw--I'm having no issues on my Switch, it's just this one user after charging a Switch with a dead battery. Any idea on what changes between 3.0 and 3.2 could've introduced this issue?

**Comment by DejaDegausser** [comment]
I've now managed to find two other users who have also run into this issue, we still haven't found a fix or what triggers it.

**Comment by yellows8** [comment]
So the date displayed in system-settings / {official sw} is correct? Starting with libnx 3.2.0 it uses the same time sharedmem as [6.0.0+] official sw.

Guess you're blocking the [aauth](https://switchbrew.org/wiki/Network#aauth) domain?

Can you get the output from `timeGetStandardSteadyClockTimePoint` and `timeGetStandardSteadyClockInternalOffset`?

**Comment by DejaDegausser** [comment]
![2021021017252700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/77202273/107586853-61984d80-6bc6-11eb-8bbd-83588ee32446.jpg)
Correct the system date and time appears completely normal in the system settings and anything that is not specifically compiled with recent versions of libnx.

**Comment by shadowninja108** [comment]
So, a workaround for the issue is to add this to `/atmosphere/config/system_settings.ini`

```ini
[time]
standard_steady_clock_test_offset_minutes = u32!0x0
```

Not a proper solution, but it's a good mitigation until this behavior is better understood.

**Comment by yellows8** [comment]
Try this, without the above workaround: https://www.dropbox.com/s/glhx95575vzj9q0/time.nro?dl=0

**Comment by DejaDegausser** [comment]
After using the above workaround I cannot replicate the issue. I tried totally deleting /atmosphere/config/system_settings.ini the the time was still correct after rebooting.

**Comment by yellows8** [comment]
What's the output from timeGetStandardSteadyClockInternalOffset now?

**Comment by DejaDegausser** [comment]
0. I tried removing the code and completely getting rid of the ini entirely and its still 0 and the time is now working correctly. Somehow that ini change seems to have permanently fixed the issue.

**Comment by yellows8** [comment]
Can someone else with the issue that hasn't used that setting try the above NRO?

**Comment by DejaDegausser** [comment]
Interesting development. I only ever launched my emunand while I had that ini tweak set, never my sysnand. My emunand's time is fixed but the sysnand still has this bug. By using my sysnand I was able to test the NRO and it seems to work correctly, it shows 17:16:20 and the correct date.
