### ISSUE TITLE
libnx 4.0.0 causing switch-curl build fails due to undefined references in library

### ISSUE THREAD

**Issue by eXhumer** [switchbrew/libnx#524]
The following error occurs while trying to build switch-curl v7.69.1 with libnx v4.0.0.
![image](https://user-images.githubusercontent.com/62310242/105270009-42bc1380-5b52-11eb-8c01-5c9ed19e4b5d.png)

Looking into the config.log generated during curl build, it looks like problems with libnx.
![image](https://user-images.githubusercontent.com/62310242/105269857-fa9cf100-5b51-11eb-98fa-0c07dc83f120.png)

Digging into libnx

https://github.com/switchbrew/libnx/blob/master/nx/source/runtime/switch_crt0.s#L86
`_DYNAMIC` used to be defined, but it was removed in commit e655b48. It seems to have been replaced by `__nx_dynamic` instead. This is most likely a bug.

https://github.com/switchbrew/libnx/blob/master/nx/source/kernel/thread.c#L19-L22
https://github.com/switchbrew/libnx/blob/master/nx/source/runtime/newlib.c#L32-L34
I found references to these variables in `nx/switch.ld` but have no clue on how they are being included in the sources linked above.

**Comment by masagrator** [comment]
Well, switch-curl is depending on libnx, not otherwise, so switch-curl needs to be updated to apply libnx changes.

**Comment by eXhumer** [comment]
@masagrator Considering that the only SSL module related change (the module that switch-curl depends on due to addition of libnx ssl backend) happened [from v3.3.0 to v4.0.0](https://github.com/switchbrew/libnx/compare/v3.3.0...v4.0.0) was [this](https://github.com/switchbrew/libnx/commit/e8a4f2206318f62e7660e5e48eb75bd8100e50c9), I find that hard to believe.

**Comment by eXhumer** [comment]
[config.log](https://github.com/switchbrew/libnx/files/5849724/config.log)

Full generated config.log from switch-curl configuration.

**Comment by eXhumer** [comment]
It works, but the provided binary only includes libnx ssl backend. This causes problem on devices that doesn't have the SSL Key in CAL0 as libnx ssl fails without a valid SSL Key. I was trying to replace --with-libnx with --with-mbedtls, but the same issue persists. After that, I noticed even the stock package from https://github.com/devkitPro/pacman-packages/tree/master/switch/curl also fails to build as well.

**Comment by yellows8** [comment]
`This causes problem on devices that doesn't have the SSL Key in CAL0 as libnx ssl fails without a valid SSL Key.` ....That was already fixed.

**Comment by eXhumer** [comment]
I last tested libnx backend on 7.69.1-2 when it was not working, I see there was a new revision since then to fix the issue with [this commit](https://github.com/devkitPro/pacman-packages/commit/1d8ef4535ff57eba73d18f2671cf3d77ba8f877c#diff-6f15902375166c2b8ee7e649ffb3fc6a15286b049ac06b1b7532d9395579e791). Thank you for letting me know libnx ssl was fixed, I'm going to close this as I can just use that. But, this bug will still be a problem for future package builds for switch-curl.
