### ISSUE TITLE
Prefix function / type names

### ISSUE THREAD

**Issue by Mstrodl** [switchbrew/libnx#528]
Hi. I'm trying to port a rather large project and using libnx. Unfortunately, libnx ends up clobbering a ton of important things used in the rest of the application (like `Event`, for example). There should be a prefix of `nx_` (or similar) on these generic names, since they can conflict with other stuff in a large project.

**Comment by fincs** [comment]
Unfortunately, while we understand that namespace conflicts can occur with such names, we are not in a position in which we can afford to break all past libnx homebrew to fit a new naming scheme. In addition, libnx is essentially the OS library used on the Switch, and OS libraries often forego any attempt to avoid namespace clashes. There are quite a lot of POSIX/Win32/etc symbols with fairly generic names that are known to collide with software not originally written for one or the other. As an alternative, I propose not including libnx headers whenever possible, and restricting usage of libnx headers to the smallest number of files (mostly the Switch specific backend that you are ostensibly working on).

**Comment by Mstrodl** [comment]
@fincs Just a suggestion, perhaps a macro could be used? Let me show you what I mean:

```c
#define LIBNX_NAMESPACE 1
#include <switch.h>
// nx_randomGet is now available
```

```c
#include <switch.h>
// both randomGet and nx_randomGet are now available
```

The actual symbols could then all use the `nx_` prefix while the "legacy" non-prefixed ones are automatically rewritten with a macro

**Comment by fincs** [comment]
That's not a desirable solution, for reasons of complexity and maintainability. Like I said, this is not really something we can really "fix" without going back in time and deciding to use less ambiguous/clashy names for system types.
