### ISSUE TITLE
hiddbgSetHdlsState not working on HOS 12.0/ATMOS 0.19.1

### ISSUE THREAD

**Issue by PaskaPinishkes** [switchbrew/libnx#542]
Hello, during the last few months, I have been making a sysmodule that heavily relies on the hiddbgSetHdlsState function on hiddbg.h
It seems like after the HOS 12.0 update, the function broke and doesn't work anymore (Result always returns failure), making virtual devices unable to be controlled.

**Comment by fincs** [comment]
This is known. We're still working on adapting libnx to the latest 12.x changes, please be patient.
