### ISSUE TITLE
Can't open file sys/lock.h

### ISSUE THREAD

**Issue by Kapitanpingwin** [switchbrew/libnx#559]
Hi.
I was trying to create some app with this but after linking includes to visual studio i had a problem title problem.
Here is my c_cpp_properties.json file: gist.github.com/Kapitanpingwin/56f31a5eb3432647a794f04482bd04c5

Help is very appreciated :)

**Comment by WinterMute** [comment]
This isn't a general support forum and this issue is unrelated to libnx. Please ask these kind of questions in devkitPro forum @ https://devkitpro.org/viewforum.php?f=42
