### ISSUE TITLE
about audoutGetReleasedAudioOutBuffer

### ISSUE THREAD

**Issue by Alklas** [switchbrew/libnx#56]
Hello

i don't know if it is an issue but i tried the following things :   
- create 2 buffers of type AudioOutBuffer
- initialize them and append them to the audio buffer
- start the audio system
- the 2 buffers play well ( no crash, sound seems ok )
- use audoutGetReleasedAudioOutBuffer
- the buffer coming from audoutGetReleasedAudioOutBuffer is not any of the 2 buffers i append before
- the released buffer is not filled with right values, or any values i setup ( size, pointer to memory buffer for sample and so on )

i thought that the logic of this audio system was : i append a buffer, the audio system uses it, and when i call getreleasedaudio , i get back a buffer i did append before ?

**Comment by plutooo** [comment]
What pointer do you get back? If you print it out?

**Comment by Alklas** [comment]
Hello,

first point : released is created as a AudioOutBuffer variable : 
AudioOutBuffer  released;
exactly as in the playtone example
( not as a pointer )

audoutGetReleasedAudioOutBuffer is called with &released and &num :
r = audoutGetReleasedAudioOutBuffer(&released, &num);

i allocate 2 memory buffers for samples :
0x76876000
0x7687a000

i create 2 buffers of type AudioOutBuffer:
0x1ea73f60
0x1ea73f88

first AudioOutBuffer values:
next = 0
buffer = 0x76876000
buffer_size = 0x2580
size = 9600
offset = 0

second AudioOutBuffer values:
next = 0
buffer = 0x7687a000
buffer_size = 0x2580
size = 9600
offset = 0

--------
each buffer is appended to audio system

the released buffer has address = 0x1ea73fd8

i wait for 3 VBLs

i get back 1 buffer ( "num" coming from getreleased = 1 ) with no error

&released still equals to : 0x1ea73fd8

released itself = 0x1ea73f20
released.next = 0x1ea73e68
released.buffer = 0
released.buffer_size = 0
released.data_size = 0
released.data_offset = 0

i wait 3 more VBLs
i getreleased 1 more buffer:

&released still equals to : 0x1ea73fd8

released itself = 0x1ea73f20
released.next = 0x1ea73e68
released.buffer = 0
released.buffer_size = 0
released.data_size = 0
released.data_offset = 0

**Comment by plutooo** [comment]
I'll relay this to hexkyz

**Comment by yellows8** [comment]
208daf6344a458b4e6ef932b31da8d758a49e5ae
