### ISSUE TITLE
Linking errors with nwindowGetDefault()

### ISSUE THREAD

**Issue by lyptt** [switchbrew/libnx#561]
I'm playing around with deko3d and I managed to get it linking via CMake by ensuring the link order is deko3d first, followed by nx, however as soon as I add `nwindowGetDefault()` it goes back to complaining about undefined references:

```
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
CMakeFiles/abc.dir/gfx/nx_renderer.cpp.obj: in function `NxRenderer::NxRenderer()':
nx_renderer.cpp:(.text._ZN10NxRendererC2Ev+0x128): undefined reference to `nwindowGetDefault()'
collect2: error: ld returned 1 exit status
```

The generated link command looks like this:

```
/opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++   -g -Wall -O2 -ffunction-sections -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE -fno-rtti -fno-exceptions -g -specs=/opt/devkitpro/libnx/include/../switch.specs (...all the objs...) -o abc  /opt/devkitpro/libnx/lib/libdeko3dd.a /opt/devkitpro/libnx/lib/libnxd.a
```

I've played around with the order of the .a's but regardless it fails to link. Is there something I'm missing here? The Makefile-based examples all build fine.

**Comment by fincs** [comment]
First of all, can you post your CMakeLists.txt? libnx is already linked in automatically as a system lib. During our testing, we found it sufficed to use this to link in deko3d:

```cmake
target_link_libraries (${PROJECT_NAME} PRIVATE
	deko3dd
)
```

**Comment by lyptt** [comment]
@fincs I managed to reproduce the issue with a basic sample. It turns out `nwindowGetDefault()` cannot be called from C++, only from C. I've attached a reproduction to this comment. If you rename `main.cpp` to `main.c` and update the CMakeLists.txt to reference it, the build will succeed, and by default it will fail.

For reference I generate a Makefile with the following command:

```bash
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake/DevkitA64Libnx.cmake ..
```

[sample.zip](https://github.com/switchbrew/libnx/files/6836576/sample.zip)

**Comment by lyptt** [comment]
Here's the full build output demonstrating the issue:

```
Scanning dependencies of target sample
[ 25%] Building CXX object CMakeFiles/sample.dir/main.cpp.obj
/Users/lyptt/Desktop/sample/main.cpp: In function 'int main()':
/Users/lyptt/Desktop/sample/main.cpp:4:12: warning: variable 'a' set but not used [-Wunused-but-set-variable]
    4 |   NWindow* a = nwindowGetDefault();
      |            ^
[ 50%] Linking CXX executable sample
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/11.1.0/../../../../aarch64-none-elf/bin/ld: DWARF error: can't find .debug_ranges section.
CMakeFiles/sample.dir/main.cpp.obj: in function `main':
main.cpp:(.text.startup.main+0x8): undefined reference to `nwindowGetDefault()'
collect2: error: ld returned 1 exit status
make[2]: *** [sample] Error 1
make[1]: *** [CMakeFiles/sample.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by fincs** [comment]
As I suspected, you're using third party/unsupported cmake machinery. You might be interested to know that, as of recently, we've added official cmake toolchain support. You can get it by installing or refreshing your switch-dev package group installation, i.e. `sudo dkp-pacman -S --needed switch-dev`.

In order to use it, we offer a wrapper script that sets the correct variables: `/opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake`. It is advised to purge your project of traces of previous unsupported machinery, and move to our new official support.

Setting up a basic project with deko3d should be as simple as this:

```cmake
cmake_minimum_required (VERSION 3.7)
project (MyProjectName)

add_executable (${PROJECT_NAME}
	# Source code files go here
	source/main.cpp
)

dkp_add_asset_target (${PROJECT_NAME}_romfs romfs)

nx_generate_nacp (${PROJECT_NAME}.nacp
	NAME "Your Project Name"
	AUTHOR "Author Name"
)

nx_create_nro (${PROJECT_NAME}
	NACP ${PROJECT_NAME}.nacp
	ROMFS ${PROJECT_NAME}_romfs
)

target_compile_options (${PROJECT_NAME} PRIVATE
	-g -Wall -O2
	$<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions -fno-rtti>
)

target_link_libraries (${PROJECT_NAME} PRIVATE
	deko3dd
)

# Shaders
nx_add_shader_program (simple_vsh simple_vsh.glsl vert)
nx_add_shader_program (simple_fsh simple_fsh.glsl frag)

dkp_install_assets (${PROJECT_NAME}_romfs
	DESTINATION shaders
	TARGETS
		simple_vsh
		simple_fsh
		# etc
)
```

**Comment by lyptt** [comment]
@fincs I've confirmed that C++ name mangling is the issue here. If it's intended that this API has C linkage, you'll need to wrap the header definitions in an extern "C" block. Doing this manually myself on my local copy of `native_window.h` fixed the linking issue.

I've attached the modified file so you can see the change.

[native_window.h.zip](https://github.com/switchbrew/libnx/files/6836595/native_window.h.zip)

**Comment by lyptt** [comment]
Thanks for a sample of the supported approach, I couldn't find any examples yesterday of using libnx with cmake when I started playing around with it, so I had to go my own route.

**Comment by fincs** [comment]
Oh and one more thing. The header you need to include is `#include <switch.h>`, which does have C++ guards. Trying to manually include libnx headers piecemeal is currently not supported.

**Comment by lyptt** [comment]
Gotcha, I didn't see any documentation relating to that quirk of the toolchain either. I'll bear that in mind from now on. Thanks for the help.
