### ISSUE TITLE
Question: Home button

### ISSUE THREAD

**Issue by XITRIX** [switchbrew/libnx#566]
Hi there!

I'm interesting, is it possible to handle home button pressing inside of app? 
I know that it's possible to prevent app from closing by using `appletBeginBlockingHomeButton(0)`, but is it possible to handle home button as any other button?

**Comment by masagrator** [comment]
https://github.com/switchbrew/libnx/blob/c5a9a909a91657a9818a3b7e18c9b91ff0cbb6e3/nx/include/switch/services/hidsys.h#L211

**Comment by masagrator** [comment]
https://github.com/WerWolv/libtesla/blob/640629f49f9e8997ef0769b21b26f4fc177c736f/include/tesla.hpp#L3440-L3458

Example usage

**Comment by fincs** [comment]
Seizing control of the HOME button isn't something regular .nro homebrew (as opposed to custom sysmodules/etc) should be doing, as it breaks the API contract Horizon enforces for regular apps.
