### ISSUE TITLE
SL/SR buttons usage on hiddbg

### ISSUE THREAD

**Issue by PaskaPinishkes** [switchbrew/libnx#567]
Hello, I was wondering how to use SL/SR buttons on an emulated controller using hiddbg. My purpose for this is to add sideways joycon support to my custom sysmodule that sends inputs from a PC to the Switch.

I have been trying different things for more than one year (I just now got the idea of asking here ;-;) and none have worked. For some reason, bits 24 through 27 (the ones used for sl and sr in left and right joycons) seem to be masked, and I can't find how to unmask them.

I made a bug report one year ago about this, but it doesn't seem to be a bug, so yeah, my question is how to unmask them, or what else can I do to emulate SL/SR (needed for games such as Clubhouse Games) on hiddbg.

If questions here are not allowed, I'm sorry and I won't repeat this mistake, I saw archived answered questions and I assumed they were allowed.

**Comment by yellows8** [comment]
The system [masks](https://switchbrew.org/wiki/HID_services#HdlsDeviceInfo) those out, so can't use those.

**Comment by PaskaPinishkes** [comment]
yeah, but on horizon os you can somehow use sl/sr anyways on physical joycons. how is this possible when they are masked?

**Comment by yellows8** [comment]
It's only masked with hiddbg.

**Comment by PaskaPinishkes** [comment]
ohhhh i see, so it's impossible to use sl and sr in hiddbg?

**Comment by yellows8** [comment]
Correct (unless someone really wanted to maintain hid-sysmodule patches for this for every required system-version...)

**Comment by PaskaPinishkes** [comment]
I see...
Thanks for the help!
