### ISSUE TITLE
hidScanInput() was not declared in this scope

### ISSUE THREAD

**Issue by EimaMei** [switchbrew/libnx#569]
I am not sure if the function was removed or I need to initialize something, but it keeps outputting the same error

**Comment by masagrator** [comment]
https://github.com/switchbrew/libnx/releases/tag/v4.1.3

```
Removed old deprecated HID API.
```

https://github.com/switchbrew/libnx/commit/637dd12b2df58c469d4e87a48aa3ebf0bc359766#diff-4a71012373c89e294ea0c50149722cdde66f0dc65f8ae9af77d7f662d042b88cL1329

Use pad instead

https://github.com/switchbrew/libnx/blob/master/nx/include/switch/runtime/pad.h

**Comment by EimaMei** [comment]
Does the pad have touchscreen support also? If so, how can I use it

**Comment by masagrator** [comment]
For touchscreen you still use hid

https://github.com/switchbrew/switch-examples/blob/master/hid/touch-screen/source/main.c

**Comment by EimaMei** [comment]
Oh okay, I’ll try the example to see if it’ll work when I get back home

**Comment by EimaMei** [comment]
It works perfectly, thanks!

**Comment by SundayReds** [comment]
sorry for bringing up an old issue, but is there any equivalent replacement for `hidKeysHeld(HidControllerID id)` ?
