### ISSUE TITLE
When i try to compile a .nro in devkitpro, i get this error:

### ISSUE THREAD

**Issue by AexHar** [switchbrew/libnx#570]
build/us_nx/bin/nacptool.o:nacptool.c:(.text.startup+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:800: build/us_nx/sm64.us.f3dex2e] Error 1
rm build/us_nx/sm64.us.f3dex2e.nacp

**Comment by masagrator** [comment]
Yeah, "NRO"... NACP error wouldn't show for someone compiling just NRO.

**Comment by AexHar** [comment]
I'm actually trying to "Render96ex" for the switch and i'm this tutorial:https://github.com/Render96/Render96ex/wiki/How-To-Compile-For-Switch but i always get that error

**Comment by fincs** [comment]
Judging by the error message, it looks like somehow you're trying to build nacptool itself; which is obviously incorrect (it's a tool we supply in the `switch-tools` package). The instructions you linked to don't seem to involve anything more than installing the necessary packages and invoking make. This therefore seems like user error.
