### ISSUE TITLE
make a relase/how to compile it

### ISSUE THREAD

**Issue by hackNcode** [switchbrew/libnx#586]
make a god damn release, if i try compiling it it doesn't work and throws errors and i am pissed off because devkitPro DOES NOT INSTALL LIBNX

**Comment by fontire** [comment]
You're an idiot.

**Comment by hackNcode** [comment]
> You're an idiot.

actually i figured out how to a while ago i was just pissed off and realized why devkitPro wouldn't install libnx, it was because it was already installed and i found a bug as if you have devkitPro already installed it won't install any other development options, jeez. tell devkitpro to fix that. anyways ima close this issue.
