### ISSUE TITLE
ASCII Usage of "\"

### ISSUE THREAD

**Issue by Cid2mizard** [switchbrew/libnx#589]
By performing tests with ASCII, I realized to de-sing a simple character this is a problem. Indeed, the character "\" is unusable while it is widely used.

```
printf("\x1b[10;10H   O ");
printf("\x1b[10;11H  /|\ ");
printf("\x1b[10;12H  / \ ");
```
Have an error `warning: unknown escape sequence: '\040'`

**Comment by WinterMute** [comment]
It's not just gcc, the \\ character is used to start an escape sequence in most languages I know. You can also see github's markdown ignoring the single slash in the OP where it displays as "\" instead of the intended "\\"
