### ISSUE TITLE
HidKeysHeld() behaviur

### ISSUE THREAD

**Issue by nop90** [switchbrew/libnx#59]
Upons subsequent hidScanInput(), with a key mantained pressed, HidKeysHeld() seems to change state (key pressed -> key not pressed -> key pressed -> ...) instead to remain steady.

Attached a simple test code. The behaviour happens on RyujiNX (I don't have a real Switch to test it) and I thought it vas an issue of the emulater, but some user reported it happens on real hw too.
[testkeys2.zip](https://github.com/switchbrew/libnx/files/1768620/testkeys2.zip)

**Comment by yellows8** [comment]
You really shouldn't remove vsync / gfx*() calls from examples ...

**Comment by nop90** [comment]
Sorry, it was a quick test. But I hope you got the point.

**Comment by yellows8** [comment]
HID should *not* be used without vsync.

**Comment by nop90** [comment]
Excuse me, I don't uderstand.

Are you saying that with vsync the problem doesn't happens (on the emulator id does) or it was a general suggestion? In the second case I agree, and that was the meaning of my previous "sorry" .

**Comment by yellows8** [comment]
in general

**Comment by yellows8** [comment]
FWIW it works fine with the read-controls example AFAIK.

**Comment by yellows8** [comment]
Does it happen when you use vsync/gfx properly?

**Comment by nop90** [comment]
I asked to test the code with the vsync/gfx part added on a real switch, and it works properly.

So I think the issue can be closed. Thanks
