### ISSUE TITLE
Problem to print special chars in console mode

### ISSUE THREAD

**Issue by shadow2560** [switchbrew/libnx#592]
Hi,

I try to display some text in the console but I accents and special chars not display correctly ("é" for example). I've tried with "printf", "wprintf", "cout" and I have tried with writing the problematic char with ASCII code, ANSI code or UTF8 code but nothing work. With "cout" I've also tested to prefix the message with u"...", U"...", L"..." or u8"..." but also no luck with this. My sources files are encoded in UTF8.

Maybe it's a font problem but I don't understand how to change it, I've seen the "ConsoleFont" type in "console.h" file but I don't understand how to set the pointer to a font and I also don't understand how to implement it. I have the pointer for my console, I know how to apply the font to it but my problem is the "ConsoleFont" type that I realy don't know how to use.

I've read a lot of things about problems of encoding with C or C++ but nothing solved my problem so I'm finaly trying to ask to you. I'm not a specialist of the C/C++ languages so sory if I have missed a basic thing.

Thanks in advance for your help.

**Comment by masagrator** [comment]
default console is designed for only ASCII support. You can draw more than ASCII characters, but after 0x7F what will be rendered depends solely on character layout in font bitmap. Default font has 256 characters.

**Comment by shadow2560** [comment]
OK so if I understand it's impossible (lets says to mutch complicated) to display accent with the console. Thanks for the help.

**Comment by fincs** [comment]
libnx's console implementation currently does not parse UTF-8 multibyte sequences, it operates on raw 8-bit code units only. The default font used by the console is based off CP437, the traditional IBM PC character set.

**Comment by shadow2560** [comment]
So, according to [this document](https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/PC/CP437.TXT), if I write:
printf("%c", 0x82);

This should display a "é" or I need something else?
