### ISSUE TITLE
Noobie question

### ISSUE THREAD

**Issue by impeeza** [switchbrew/libnx#646]
Hello there,  

When installing the official release using devkitPro Pacman you got versions like «libnx-4.7.0-1»  how can you tell which commit is that version?

thanks a lot.

**Comment by masagrator** [comment]
usually by looking at Releases page, but for some reason it wasn't uploaded to Releases.

**Comment by WinterMute** [comment]
Every release is tagged as part of the release process. Nothing is uploaded to Releases.

https://github.com/switchbrew/libnx/tags

**Comment by impeeza** [comment]
Thank you so much guys.
