### ISSUE TITLE
What is the relationship between the game save data info's uid and the account's uid

### ISSUE THREAD

**Issue by iamcco** [switchbrew/libnx#648]
I don't know if it's the right place to ask the question, feel free to close.

There are 7 accounts in the switch for example 1, 2.....7.

Account 1 and it's uid is: uid(1).

If use account 1 to play, the game save data info's uid is uid(11) which doesn't match the uid(1) of the account 1.
> if call `accountProfileGet` with the uid(11), the result's account profile's uid which is the uid(1) of the account 1.

if use the other account (2....7) to play, the game save data info's uid which is the uid of the account (2....7).

So what is the relationship between the game save data info's uid and the account's uid? Will an account have many associated uids?

**Comment by yellows8** [comment]
If there's really account uid aliases not aware of it. Only aware of 1 Uid per account.

For general support see [forums](https://devkitpro.org/index.php).
