### ISSUE TITLE
Error 2345-0021: libnx failed to map code memory

### ISSUE THREAD

**Issue by Azure-Agst** [switchbrew/libnx#86]
I was using fusee/hekate to launch Homebrew Launcher 2.0 on my switch (vers 5.0.2) and all seemed to work well. HBL would launch, I could launch other .nro's using it (specifically TuxSH's ftpd) but after a while I started getting error `2345-0021`. After consulting to the wiki, I determined this was due to libnx failing to map the code memory. It's happening consistently now, within seconds of homebrew launching, the app will spew the error.

Since the error code pinned its problem on libnx, I figured I'd create an issue here to resolve the problem. Below are the steps to reproduce.

1. Download files from [Jan4V/hekate-ipl-50x](https://github.com/Jan4V/hekate-ipl-50x/releases).
2. Place contents of zip on the root of SD. Insert card into switch.
3. Boot into RCM and flash the payload from earlier using fusee-launcher. Boot into CFW.
4. Launch the album applet. After using FTPD for a while, my switch seemed to start crashing.

If there's anything else you all need of me or any way I can help, let me know!

**Comment by yellows8** [comment]
hbl errors != libnx errors

**Comment by fincs** [comment]
Seems to be a duplicate of #77

**Comment by Azure-Agst** [comment]
Actually no, I fixed it. Seems it wasn't a HBL or libnx error. My SD card managed to only mount itself in read-only which caused some errors with libnx, causing the error code. (It was hidden at first, since games from the sd still seemed to run with no error.) After reformatting, the sd card seemed to work again and no errors.

**Comment by 877cms** [comment]
@Azure-Agst how did you determine that the card was mounted in read-only?

**Comment by Azure-Agst** [comment]
@877cms it's been a bit, but iirc I tried using FTP to upload files, and it would always spew an error. Plugging it into PC also wouldn't let me write. After reformatting, both FTP and plugging it in let me write files again.
