### ISSUE TITLE
when trying to use crop on horizontal resolution, switch crashes

### ISSUE THREAD

**Issue by Alklas** [switchbrew/libnx#89]
hello

with the following code, i am able to create a crop at the top of the screen, so that the first 12 lines are not displayed : 

        gfxConfigureCrop(0, 12, 0, 0); 
        gfxInitResolution(1280, 732);
        gfxConfigureResolution(1280,720);
        gfxInitDefault();

checking for resolution, i get 1280*732

but when using this , to have an horizontal crop : 

        gfxConfigureCrop(32, 12, 0, 0); 
        gfxInitResolution(1280+32, 732);
        gfxConfigureResolution(1280,720);
        gfxInitDefault();

i get a crash with error 2345-0018

am i missing a point ? or is it a bug ?

thanks

my switch is 3.0.0, running HBL through pegaswitch

**Comment by fincs** [comment]
Seems to be `LibnxError_BadGfxInit`

**Comment by Alklas** [comment]
i made more tests
it seem to zoom the graphical display to fit in the crop part
i thin ki misunderstood the use of crop
i am searching for a way to have a larger screen but with a 1280*720 display, with borders not displayed
for example a line of 1600 pixels, with 1280 displayed and the ability to move the frame buffer start

if you have advices for this, they are welcome.

thanks

**Comment by yellows8** [comment]
```
gfxInitResolutionDefault();
gfxInitDefault();
...
gfxConfigureCrop(...);
```
