### ISSUE TITLE
no sys/lock.h file required by mutex.h

### ISSUE THREAD

**Issue by PyroFlareX** [switchbrew/libnx#93]
As you likely know, mutex.h is required by switch.h, so it is impossible to do much in a coding environment that passively creates errors. Any address to the issue?

**Comment by fincs** [comment]
I don't understand this issue at all. mutex.h does have a dependency on sys/lock.h, and said file does exist. What's the issue here?

**Comment by PyroFlareX** [comment]
![screenshot_2018-05-16_12-29-36](https://user-images.githubusercontent.com/31327816/40139477-d4a36be8-5904-11e8-9d2a-639a6fb1b5d9.png)

**Comment by PyroFlareX** [comment]
this is what is meant

**Comment by fincs** [comment]
That's a problem with your VSCode project configuration, it has nothing to do with libnx.
